services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmStatDB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U USER -d ewmStatDB" ]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 60s

  stats-server:
    build: ./stat_svc
    container_name: ewm_stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    restart: on-failure        # автоматический перезапуск при падении
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stat-db:5432/ewmStatDB
      - SPRING_DATASOURCE_USERNAME=USER
      - SPRING_DATASOURCE_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9090/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 120s

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=ewmMainDB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U USER -d ewmMainDB" ]
      interval: 5s           # чаще проверяем
      timeout: 3s
      retries: 15            # больше попыток
      start_period: 45s      # время на старт

  ewm-service:
    build: ./main_svc
    container_name: ewm_main_server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmMainDB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s

networks:
  ewm-network:
    name: ewm-network
    driver: bridge