version: '3.8'

services:
  stats-server:
    build: ./stat_svc
    container_name: ewm_stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmStatDB
      - SPRING_DATASOURCE_USERNAME=USER
      - SPRING_DATASOURCE_PASSWORD=1234
    # Ждать готовности БД
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U USER -d ewmStatDB -h stats-db" ]
      interval: 10s
      timeout: 5s
      retries: 10

  stats-db:
    image: postgres:16.1
    container_name: ewm-stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmStatDB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres-stats-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U USER -d ewmStatDB" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres-stats-data:
