services:
  stats-db:
    image: postgres:16.1
    container_name: ewm-stat-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmStatDB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U USER -d ewmStatDB" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 120s  # Даём на полную инициализацию

  stats-server:
    build: ./stat_svc
    container_name: ewm_stat_server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    restart: on-failure
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewmStatDB
      - SPRING_DATASOURCE_USERNAME=USER
      - SPRING_DATASOURCE_PASSWORD=1234
      # Увеличиваем таймаут подключения к БД
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=60000  # 60 секунд
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -f http://localhost:9090/actuator/health || exit 1"
      ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 180s  # Ждём до 3 минут перед первой проверкой
    # Ключевое: задержка старта на 120 секунд
    entrypoint: [
      "/bin/sh", "-c",
      "sleep 30 && java -jar /app/app.jar"
    ]

  ewm-db:
    image: postgres:16.1
    container_name: ewm-main-db
    ports:
      - "7654:5432"
    environment:
      - POSTGRES_DB=ewmMainDB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=1234
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U USER -d ewmMainDB" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 120s

  ewm-service:
    build: ./main_svc
    container_name: ewm_main_server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmMainDB
      - POSTGRES_USER=USER
      - POSTGRES_PASSWORD=1234
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=60000
    healthcheck:
      test: [
        "CMD-SHELL",
        "curl -f http://localhost:8080/actuator/health || exit 1"
      ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 180s